### ISSUE TITLE
Document how to generate documentation for multiple GraphQL URLs

### ISSUE THREAD

**Issue by yashvcomply** [magidoc-org/magidoc#184]
I have several APIs in my AppSync, hence different Graphql API urls how can I generate a common documentation using magidoc?
<img width="1512" alt="Screenshot 2023-01-25 at 15 00 53" src="https://user-images.githubusercontent.com/103980623/214528489-b9855c1d-9bba-466e-8dd7-8023533b7655.png">

**Comment by pelletier197** [comment]
Hi @yashvcomply, thanks for opening this issue. 

Magidoc doesn't support `multiple-schemas` out of the box, and it's not really planned to do it through one configuration because of the complexity it brings to customize the configuration for one of the websites only.  

What we instead recommend is to generate multiple documentation websites, and to link them together using `externalLinks` configuration. See the `externalLinks` property in the [documentation](https://magidoc.js.org/cli/magidoc-configuration#website).

For reference, external links will show up on the right navigation. 
![image](https://user-images.githubusercontent.com/24528884/214572002-78c08ad6-1e50-4723-b51c-14b468bb2878.png)


You have an example [here](https://github.com/magidoc-org/magidoc/tree/main/packages/examples/multi-schema) using 2 GraphQL APIs. So the idea is to repeat the same thing with 9 APIs in your case. 

Hope this help, let me know if this fixes your issue or if you have a feature request related to this. For now, I think it would be a great idea to at least add this to the documentation.

**Comment by yashvcomply** [comment]
Thanks @pelletier197 that was an extensive explanation. I'll surely check for external linking and see how it works for me. Thanks for taking out the time to help with this one.  Appreciate it. 🤝

**Comment by pelletier197** [comment]
Hi @yashvcomply. Did you manage to make your use-case work? If yes, can we close this issue ?

**Comment by pelletier197** [comment]
I just merged #191 which will point to the example I gave you here. I'm closing this as resolved, but let me know if you need more details. Thank you!
