### ISSUE TITLE
Relative URLs not supported in markdown

### ISSUE THREAD

**Issue by TomHAnderson** [magidoc-org/magidoc#348]
### Describe the bug

Possibly related to #337, I cannot reference an image with a relative URL in markdown

### Reproduction

```markdown
![Entity Relationship Diagram](/erd.png "Entity Relationship Diagram")
```

### Logs

```shell
Command 'pnpm' failed with status 1 when executed in directory /tmp/carbon-multi-page@4.2.1

---- Program Output----

> @magidoc/starter-carbon-multi-page@4.2.1 build /tmp/carbon-multi-page@4.2.1
> svelte-kit sync && vite build

vite v5.2.7 building SSR bundle for production...
transforming...
"GraphQLDirective", "GraphQLInterfaceType" and "GraphQLObjectType" are imported from external module "graphql" but never used in "src/lib/components/tags/NullableTag.svelte", "src/lib/components/common/text/TypeLink.svelte", "src/lib/components/tags/DirectiveTag.svelte", "src/lib/model.ts", "src/lib/components/tags/TypeTag.svelte" and "src/routes/types/[type]/+page.svelte".
```

### System Info

```shell
System:
    OS: Linux 6.6 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (10) arm64 unknown
    Memory: 10.60 GB / 11.67 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.19.0 - /usr/bin/node
    npm: 9.2.0 - /usr/bin/npm
    pnpm: 9.0.2 - /usr/local/bin/pnpm
```
```


### Severity

Blocking all usage of Magidoc

**Comment by pelletier197** [comment]
Have you tried putting your root path in the relative image path? I believe this might fix the problem temporarily. 

I'll have a look if it's possible to use the site root in there. I remember there were limitations in the past with this, but I don't remember very well what they were.

**Comment by TomHAnderson** [comment]
Putting a fully qualified URL in like http://localhost/erd.png works.  So too does https://path.to.deployment/erd.png but `/erd.pdf` does not.  I would like the docs generated with relative paths.

**Comment by pelletier197** [comment]
@TomHAnderson sorry for the late comeback. I though your issue was with base path URLs, but I'm not sure anymore. 

2 Questions 
- Do you have a site root (in your configuration)? `website.options.siteRoot` 
- Do you use static assets (with your image inside it)? `website.staticAssets` 

If your image is hosted outside of your website, it's normal for the generation to fail. The template used to build the website tries to resolve every URL of the website to make sure everything works well. If you wish to point to something external to the website, you'll need to use raw HTML directly inside the markdown.

```html
<img src="/erd.png" rel="external" />
```

I do however recommend using static assets if possible.

**Comment by Magdi7amed** [comment]
🥹_

**Comment by Magdi7amed** [comment]
![received_1498358390220813.jpg](https://github.com/magidoc-org/magidoc/assets/161584821/21ba0cc5-5118-4e19-b1c5-8ab9058cfcc9)

**Comment by pelletier197** [comment]
Any news on this ? Did this resolve your issue ? I'll be closing this otherwise

**Comment by TomHAnderson** [comment]
I'm OK closing this.
