### ISSUE TITLE
Refreshing the browser results in 404

### ISSUE THREAD

**Issue by gioragutt** [magidoc-org/magidoc#99]
When I go to one of the documentation pages, say this: https://magidoc-carbon-multi-page.netlify.app/queries/findListByID, the browser ends up turning the url to lowercase, which probably breaks routing.

I tried this on Chrome, went to a page from the UI, and after I refresh the tab it results in 404.

I did it with "Paste and Go" in Safari and got the same result immediately (it probably lower-cased the url as part of the operation)

I'm using Chrome and Safari in iOS 15.5

**Comment by pelletier197** [comment]
Thanks for raising the issue. I did notice this problem before. This is not a bug in Magidoc, but rather an interesting feature of `Netlify`, the platform used for hosting the demo. See [this post](https://answers.netlify.com/t/my-url-paths-are-forced-into-lowercase/1659) for reference. 

Since magidoc uses the `slug` in the URL (`findListByID`) to determine the query to display, when Netlify converts it to lower-case, the type cannot be found. 

The solution to this could be to match fields by name ignoring the case, but this causes another issue. In GraphQL the type `id` and `ID` can both exist at the same time, because GraphQL names are [case-sensitive](https://spec.graphql.org/June2018/#sec-Names).  

So for the issue, the only solution seems to be to change the hosting platform. I would rather follow GraphQL's specification than deal with an annoying feature of one platform.

Does that make sense, or do you have another possible solution in mind to this problem?

**Comment by gioragutt** [comment]
Hmm... Considering you can't **really** know where the generated site will be hosted, perhaps a wikipedia-like approach can be taken, where you keep track of documents with similar lower-case names, and you'd present the user with a list of possible "articles", and then it would be SPA routing from there.

It's still a shitty experience if you reload again, but it is a way to handle imposed duplicates

**Comment by pelletier197** [comment]
That's not a bad idea. I'll try to see if I find better, but in which case, this is better than just dropping Netlify.

Plus, let's be fair, I really doubt people usually have two types with the name name in a different case. That would be a little messed up.

**Comment by pelletier197** [comment]
For now, I took the decision to make the fields match ignoring case. I did not implement the Wikipedia approach for now, because the added complexity, as small as it may be, is not worth the investment considering that there may be extremely rare occasions where you want to have two types with the same name but with a different case.

The fix is already deployed, thanks for raising the issue!
